name: Build docker image
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      - name: Build artifact
        run: mvn package
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: target/*.jar
      - name: Build Docker image
        run: docker build -t myspb .
